// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLqfhaad56r69wxM3kbvf3q0VRIpWLEg',
    appId: '1:520354700454:web:d6cb0e6ff813a860062867',
    messagingSenderId: '520354700454',
    projectId: 'expense-tracker-app-2k26',
    authDomain: 'expense-tracker-app-2k26.firebaseapp.com',
    storageBucket: 'expense-tracker-app-2k26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2npIm6e9Q0qMg_dRx3KtNiRG_ia4vdD0',
    appId: '1:520354700454:android:9b6c480ed075d268062867',
    messagingSenderId: '520354700454',
    projectId: 'expense-tracker-app-2k26',
    storageBucket: 'expense-tracker-app-2k26.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2yi_KgPy7g3DS9sn1WDYq-zzbn9HMQJM',
    appId: '1:426249064765:ios:6eddfbf419ac2d7ec17554',
    messagingSenderId: '426249064765',
    projectId: 'expense-62f73',
    storageBucket: 'expense-62f73.firebasestorage.app',
    iosClientId: '426249064765-vumhe6vkr034ak62itt0j4l3dkat2ck8.apps.googleusercontent.com',
    iosBundleId: 'com.krishpatel.expenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6IpUy5adszSxihXHBBKEvXTIM3GuR7w',
    appId: '1:520354700454:ios:3133d5c27cbac03f062867',
    messagingSenderId: '520354700454',
    projectId: 'expense-tracker-app-2k26',
    storageBucket: 'expense-tracker-app-2k26.firebasestorage.app',
    androidClientId: '520354700454-bso1sdi4t8s717i4qhaqbol8ljnt6kak.apps.googleusercontent.com',
    iosClientId: '520354700454-6f9adnjig2ls8j8guhrm4qg8bn07e9ab.apps.googleusercontent.com',
    iosBundleId: 'com.krishpatel.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJLqfhaad56r69wxM3kbvf3q0VRIpWLEg',
    appId: '1:520354700454:web:3eba333f5ffa1403062867',
    messagingSenderId: '520354700454',
    projectId: 'expense-tracker-app-2k26',
    authDomain: 'expense-tracker-app-2k26.firebaseapp.com',
    storageBucket: 'expense-tracker-app-2k26.firebasestorage.app',
  );
}
